name: Update Activity

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Update recent activity"
          MAX_LINES: 5
          TARGET_FILE: README.md
